"""Generative model for HeartSteps-like simulation trajectories.

Constructs a generative model from NHANES-like step count data that simulates
the data-generating process described in Section 6.1 of the HeartSteps V2 paper.

For each participant, a 90-day sequence is generated by:
1. Extending 7-day data to 90 days via concatenation of randomly selected days
2. Applying a linear reward model: R_t = g(S_t)^T * alpha + A_t * f(S_t)^T * beta + epsilon_t
3. Simulating availability I_t ~ Bernoulli(p_avail)
4. Simulating anti-sedentary suggestions with probability p_sed

Reference:
    Liao et al. (2019). arXiv:1909.03539, Section 6.1.
"""

from __future__ import annotations

import logging

import numpy as np

logger = logging.getLogger(__name__)


class GenerativeModel:
    """Generative model for simulating HeartSteps-like trajectories.

    Takes step count data and parameters, and generates synthetic trajectories
    with availability, actions, and rewards.

    Attributes:
        step_data: Source step count data (n_participants, n_days, n_windows).
        alpha: Baseline reward coefficients.
        beta: Treatment effect coefficients.
        noise_variance: Variance of observation noise.
        p_avail: Probability of being available at a decision time.
        p_sed: Probability of anti-sedentary suggestion between decision times.
    """

    def __init__(
        self,
        step_data: np.ndarray,
        alpha: np.ndarray,
        beta: np.ndarray,
        g_dim: int = 8,
        noise_variance: float = 1.0,
        p_avail: float = 0.85,
        p_sed: float = 0.2,
        seed: int = 42,
    ) -> None:
        """Initialise generative model.

        Args:
            step_data: Source data (n_participants, n_days, n_windows).
            alpha: Reward coefficients [alpha_0 (g_dim), alpha_1 (f_dim)].
            beta: Treatment effect coefficients, length f_dim.
            g_dim: Dimension of baseline features g(s).
            noise_variance: Observation noise variance sigma^2.
            p_avail: Availability probability. Default 0.85.
            p_sed: Anti-sedentary suggestion probability. Default 0.2.
            seed: Random seed.
        """
        self.step_data = step_data
        self.alpha = alpha
        self.beta = beta
        self.g_dim = g_dim
        self.f_dim = len(beta)
        self.noise_variance = noise_variance
        self.p_avail = p_avail
        self.p_sed = p_sed
        self._rng = np.random.default_rng(seed)
        self._seed = seed

        self._n_participants, self._n_source_days, self._n_windows = step_data.shape

        logger.debug(
            "GenerativeModel initialised: %d participants, %d source days, "
            "%d windows, alpha=%s, beta=%s",
            self._n_participants,
            self._n_source_days,
            self._n_windows,
            alpha,
            beta,
        )

    def _extend_to_90_days(self, participant_idx: int) -> np.ndarray:
        """Extend participant's data from source days to 90 days.

        Concatenates randomly selected days until reaching 90 days.
        Random selection is done once and fixed for reproducibility.

        Args:
            participant_idx: Index of the participant.

        Returns:
            Array of shape (90, n_windows).
        """
        source = self.step_data[participant_idx]
        n_source = source.shape[0]
        days_needed = 90 - n_source

        if days_needed <= 0:
            return source[:90]

        # Randomly select additional days
        extra_indices = self._rng.integers(0, n_source, size=days_needed)
        extra_days = source[extra_indices]

        return np.concatenate([source, extra_days], axis=0)

    def _construct_features(
        self, steps: np.ndarray, t: int, daily_steps_t: float, time_slot: int, day: int
    ) -> tuple[np.ndarray, np.ndarray]:
        """Construct baseline and treatment feature vectors.

        Baseline features g(s) (8 dims):
          1. steps_30min_norm:   current 30-min steps / 500
          2. steps_1hr_norm:     rolling 1hr average / 500
          3. steps_2hr_norm:     rolling 2hr average / 500
          4. steps_24hr_norm:    rolling 24hr average / 10000
          5. daily_steps_norm:   cumulative daily steps / 10000
          6. time_of_day_sin:    sin(2*pi*time_slot/5)
          7. time_of_day_cos:    cos(2*pi*time_slot/5)
          8. day_of_week_sin:    sin(2*pi*(day%7)/7)

        Treatment features f(s) (4 dims):
          1. steps_30min_norm:   current steps (captures immediate response)
          2. step_variability:   std of last 6 windows / 100
          3. time_of_day_sin:    sin encoding
          4. daily_total_norm:   daily total / 10000

        Args:
            steps: Full flattened step array.
            t: Current time index.
            daily_steps_t: Cumulative daily steps estimate.
            time_slot: Decision time slot (0-4).
            day: Study day (0-89).

        Returns:
            Tuple of (g_features, f_features) as numpy arrays.
        """
        steps_30min = float(steps[t])

        # Rolling step averages
        lookback_1hr = max(0, t - 1)
        lookback_2hr = max(0, t - 3)
        lookback_24hr = max(0, t - 47)

        steps_1hr = float(np.mean(steps[lookback_1hr : t + 1]))
        steps_2hr = float(np.mean(steps[lookback_2hr : t + 1]))
        steps_24hr = float(np.mean(steps[lookback_24hr : t + 1]))

        # Step variability (std of last 6 windows)
        lookback_var = max(0, t - 5)
        n_var = t - lookback_var + 1
        step_var = float(np.std(steps[lookback_var : t + 1])) if n_var >= 2 else 0.0

        # Normalise to [0, 1]
        steps_30min_norm = min(steps_30min / 500.0, 1.0)
        steps_1hr_norm = min(steps_1hr / 500.0, 1.0)
        steps_2hr_norm = min(steps_2hr / 500.0, 1.0)
        steps_24hr_norm = min(steps_24hr / 10000.0, 1.0)
        daily_norm = min(daily_steps_t / 10000.0, 1.0)

        # Cyclical encodings
        time_of_day_sin = np.sin(2.0 * np.pi * time_slot / 5.0)
        time_of_day_cos = np.cos(2.0 * np.pi * time_slot / 5.0)
        day_of_week_sin = np.sin(2.0 * np.pi * (day % 7) / 7.0)

        g = np.array(
            [
                steps_30min_norm,
                steps_1hr_norm,
                steps_2hr_norm,
                steps_24hr_norm,
                daily_norm,
                time_of_day_sin,
                time_of_day_cos,
                day_of_week_sin,
            ]
        )

        step_var_norm = min(step_var / 100.0, 1.0)

        f = np.array(
            [
                steps_30min_norm,
                step_var_norm,
                time_of_day_sin,
                daily_norm,
            ]
        )

        return g, f

    def generate_trajectory(self, participant_idx: int, n_days: int = 90) -> dict:
        """Generate a single trajectory for a participant.

        Produces a 90-day sequence of (context, availability, actions, rewards)
        following the generative model in Section 6.1.

        Args:
            participant_idx: Index of the participant.
            n_days: Number of days to generate (default 90).

        Returns:
            Dict with keys:
            - steps: (n_days * n_windows,) 30-min step counts
            - availabilities: (n_days * n_windows,) boolean availability
            - actions: (n_days * n_windows,) binary actions
            - rewards: (n_days * n_windows,) observed rewards
            - times: (n_days * n_windows,) time slot indices
        """
        n_windows = self._n_windows
        total_times = n_days * n_windows

        data = self._extend_to_90_days(participant_idx)
        steps = data.flatten()

        # Reward features
        rewards = np.zeros(total_times)
        availabilities = np.full(total_times, True)
        actions = np.zeros(total_times, dtype=int)

        # Daily step accumulator
        daily_steps = np.zeros(total_times, dtype=float)

        for t in range(total_times):
            day = t // n_windows
            time_slot = t % n_windows // 2  # 5 decision times per day

            # Availability (not available during night slots)
            window = t % n_windows
            is_night = window < 1 or window >= 9
            availabilities[t] = (
                False if is_night else self._rng.binomial(1, self.p_avail) == 1
            )

            # Update daily steps
            if time_slot == 0:
                daily_steps[t] = steps[max(0, t - n_windows) : t].sum()
            else:
                daily_steps[t] = daily_steps[max(t - n_windows, 0)]

            # Construct features
            g, f = self._construct_features(steps, t, daily_steps[t], time_slot, day)

            # Generate action (simple rule: 30% probability when available)
            if availabilities[t]:
                actions[t] = self._rng.binomial(1, 0.3)

            # Generate reward
            alpha_0 = self.alpha[: self.g_dim]
            alpha_1 = self.alpha[self.g_dim :]
            R_base = g @ alpha_0 + f @ alpha_1
            R_treat = actions[t] * f[: len(self.beta)] @ self.beta
            epsilon = self._rng.normal(0, np.sqrt(self.noise_variance))
            rewards[t] = R_base + R_treat + epsilon

        return {
            "steps": steps,
            "availabilities": availabilities,
            "actions": actions,
            "rewards": rewards,
            "times": np.arange(total_times),
        }
